Correction du document 'phi1363.phi002.digilibLT-lat1.xml'
Chartes-TNAH/digiliblt pull request #4
Opened 2021-04-01 12:53 UTC by Ammeister

Corrections apportées au documents 'phi1363.phi002.digilibLT-lat1.xml' : 
- Correction du Xpath généré automatiquement par CapiTainS.
- Correction de l'identifiant renvoyant au latin dans le TEI-Header (la -> lat).

(Modification de la verbosité du Hooktest à 7.

2021-04-01 15:33 UTC, PonteIneptique requested changes

2021-04-01 15:33 UTC, PonteIneptique commented on data/phi1363/phi002/phi1363.phi002.digilibLT-lat1.xml
> +        <cRefPattern n="unknown" matchPattern="(\w+)"
Ici cela devrait être "section", c'est annoncé dans les `@type` de div

2021-04-01 15:33 UTC, PonteIneptique commented on data/phi1363/phi002/phi1363.phi002.digilibLT-lat1.xml
> +      <change who="Hippolyte Souvay" when="2021-03-27">Correction du Xpath généré par CapiTainS.</change>
+ réindentation a première vue

2021-04-01 15:38 UTC, PonteIneptique commented
Alors, vous passez le premier, du coup, vous avez un bonus vu que vous n'avez pas les corrections des autres. :1st_place_medal: 

- La PR est globalement bonne, un lien vers l'issue #2 aurait été encore mieux
- Les commits, si je les lis sans savoir quel fichier vous avez changé, sont peu compréhensibles. Quand vous corrigez un fichier, et que vous créez un commit, ajoutez un élément dans le message du commit qui permette d'identifier le fichier, tel que phi1363.002 par exemple 

Point positif:
- Communication par github
- Bonne utilisation de HookTest
- Bonne utilisation des balises TEI
- Bonne séparation en étapes des commits.

4/4 avec le bonus primo-arrivant dès que vous aurez corrigé les points mentionnés plus haut en review de cette PR.

2021-04-01 21:50 UTC, Ammeister commented on data/phi1363/phi002/phi1363.phi002.digilibLT-lat1.xml
> +        <cRefPattern n="unknown" matchPattern="(\w+)"
`       <cRefPattern n="unknown" matchPattern="(\w+)"
        <cRefPattern n="section" matchPattern="(\w+)"
          replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@n='$1'])">
          <p>This pointer pattern extracts unknwon</p>
          <p>This pointer pattern extracts sections</p>`

2021-04-01 21:56 UTC, Ammeister commented on data/phi1363/phi002/phi1363.phi002.digilibLT-lat1.xml
> +        <cRefPattern n="unknown" matchPattern="(\w+)"
J'ai pull la modification de la verbosité que j'avais faite en ligne en local et j'ai procédé aux modifications ainsi qu'à leur documentation. J'ai rédigé les commits et push le tout sur ma branche master. Les commits sont bien pris en compte par cette PR, mais je n'arrive pas à faire figurer ma réponse ici :/
C'est bon pour vous ?

2021-04-02 05:36 UTC, PonteIneptique commented on data/phi1363/phi002/phi1363.phi002.digilibLT-lat1.xml
> +        <cRefPattern n="unknown" matchPattern="(\w+)"
C'est bon, regardez d'ailleurs, c'est marqué _outdated_:
![image](https://user-images.githubusercontent.com/1929830/113384318-13155d00-9386-11eb-9aec-934730636ccc.png)

2021-04-02 05:36 UTC, PonteIneptique commented
Cette PR est bonne. Dommage que vous n'en ayez pas profité pour appliquer ma remarque sur les messages de commit... ;)

2021-04-02 06:08 UTC, PonteIneptique commented
Dernier commentaire: vous devriez vraiment travailler sur des branches. Je prévois des problèmes rapidement ;)

2021-04-02 06:08 UTC, merged